- id: coffee_hang
  emoji: â˜•ï¸
  name: Coffee Hangout
  description: Let's meet for coffee and talk about life.
- id: sunset_reflections
  emoji: ğŸŒ…
  name: Sunset Reflections
  description: >-
    We'll go to my favorite sunset spot, share some snacks, and do some
    journaling. After, we'll share what we journaled about :>
- id: coworking_session
  emoji: ğŸ’»
  name: Coworking Session
  description: >-
    Let's meet at a coffee shop and work on our passion projects together!
- id: ice_cream_hang
  emoji: ğŸ¦
  name: Ice Cream Hang!!
  description: Let's grab an ice cream and vibe at a nearby park :)
